[package]
name = "optipng"
version = "0.1.0"
description = "OptiPNG is a PNG optimizer that recompresses image files to a smaller size, without losing any information"
readme = "README.md"
repository = "https://github.com/wapm-packages/optipng"

[[module]]
name = "optipng"
source = "optipng.wasm"
abi = "emscripten"

[[command]]
name = "optipng"
module = "optipng"
